[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "C31hQ3iWGT8btkTFSwKCSnjSqwzz9GStV3YEGq9fQQ4T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/alex/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
